//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pokemon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class friends
    {
        public int friendEntryId { get; set; }
        public int player1_id { get; set; }
        public int player2_id { get; set; }
        public Nullable<int> friendStatus { get; set; }
        public Nullable<System.DateTime> updated { get; set; }
    
        public virtual Players Players { get; set; }
        public virtual Players Players1 { get; set; }
    }
}
