//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pokemon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Players
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Players()
        {
            this.friends = new HashSet<friends>();
            this.friends1 = new HashSet<friends>();
            this.PokemonsDetails = new HashSet<PokemonsDetail>();
            this.Trade_pokemon = new HashSet<Trade_pokemon>();
            this.Trade_pokemon1 = new HashSet<Trade_pokemon>();
        }
    
        public int playerID { get; set; }
        public string playerName { get; set; }
        public string city { get; set; }
        public Nullable<int> points { get; set; }
        public Nullable<int> profileID { get; set; }
        public Nullable<int> avatar { get; set; }
        public string password { get; set; }
        public string country { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<friends> friends { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<friends> friends1 { get; set; }
        public virtual Profile Profiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PokemonsDetail> PokemonsDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trade_pokemon> Trade_pokemon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trade_pokemon> Trade_pokemon1 { get; set; }
    }
}
