//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pokemon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PokemonsDetail
    {
        public int pokemonDetail_ID { get; set; }
        public Nullable<int> pokemonID { get; set; }
        public Nullable<int> playerID { get; set; }
        public Nullable<System.DateTime> entryDate { get; set; }
    
        public virtual Players Players { get; set; }
    }
}
