//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pokemon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trade_pokemon
    {
        public int tradeID { get; set; }
        public Nullable<int> requestSentTo { get; set; }
        public Nullable<int> trade_PokemonID { get; set; }
        public Nullable<int> request_by { get; set; }
        public Nullable<int> trade_by_PokemonID { get; set; }
        public Nullable<bool> trade_status { get; set; }
        public Nullable<System.DateTime> dateRequest { get; set; }
    
        public virtual Players Players { get; set; }
        public virtual Players Players1 { get; set; }
    }
}
